services:
  - type: web
    plan: free
    healthCheckPath: /health_check
    name: cautious_octo_fishstick
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
      - key: RAILS_MASTER_KEY
        sync: false